name: ASP.NET Web API CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore PseudoCRMAPI/PseudoCRMAPI.csproj

    - name: Build
      run: dotnet build PseudoCRMAPI/PseudoCRMAPI.csproj --configuration Release

    - name: Test
      run: dotnet test PseudoCRMAPI/PseudoCRMAPI.csproj --logger "trx;LogFileName=testresults.xml"

    - name: Publish
      run: dotnet publish PseudoCRMAPI/PseudoCRMAPI.csproj --configuration Release --output publish

    #- name: Deploy to Azure Web App
    #  uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: 'your-app-name'
    #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #    package: './PseudoCRMAPI/publish'
